/*
This file is part of Envision.

Envision is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Envision is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Envision.  If not, see <http://www.gnu.org/licenses/>

Copywrite 2012 - Oregon State University

*/
/* soapH.h
   Generated by gSOAP 2.7.16 from EnvWebServices.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || soap_put_LONG64(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__GetStudyAreaVersionResponse
#define SOAP_TYPE__ns1__GetStudyAreaVersionResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetStudyAreaVersionResponse(struct soap*, const char*, int, const _ns1__GetStudyAreaVersionResponse *, const char*);
SOAP_FMAC3 _ns1__GetStudyAreaVersionResponse * SOAP_FMAC4 soap_in__ns1__GetStudyAreaVersionResponse(struct soap*, const char*, _ns1__GetStudyAreaVersionResponse *, const char*);

#define soap_write__ns1__GetStudyAreaVersionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetStudyAreaVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetStudyAreaVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaVersionResponse * SOAP_FMAC4 soap_get__ns1__GetStudyAreaVersionResponse(struct soap*, _ns1__GetStudyAreaVersionResponse *, const char*, const char*);

#define soap_new__ns1__GetStudyAreaVersionResponse(soap, n) soap_instantiate__ns1__GetStudyAreaVersionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetStudyAreaVersionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetStudyAreaVersionResponse * SOAP_FMAC2 soap_instantiate__ns1__GetStudyAreaVersionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetStudyAreaVersionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetStudyAreaVersion
#define SOAP_TYPE__ns1__GetStudyAreaVersion (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetStudyAreaVersion(struct soap*, const char*, int, const _ns1__GetStudyAreaVersion *, const char*);
SOAP_FMAC3 _ns1__GetStudyAreaVersion * SOAP_FMAC4 soap_in__ns1__GetStudyAreaVersion(struct soap*, const char*, _ns1__GetStudyAreaVersion *, const char*);

#define soap_write__ns1__GetStudyAreaVersion(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetStudyAreaVersion(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaVersion * SOAP_FMAC4 soap_get__ns1__GetStudyAreaVersion(struct soap*, _ns1__GetStudyAreaVersion *, const char*, const char*);

#define soap_new__ns1__GetStudyAreaVersion(soap, n) soap_instantiate__ns1__GetStudyAreaVersion(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetStudyAreaVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetStudyAreaVersion * SOAP_FMAC2 soap_instantiate__ns1__GetStudyAreaVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetStudyAreaVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetStudyAreaSetupDateTimeResponse
#define SOAP_TYPE__ns1__GetStudyAreaSetupDateTimeResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, const char*, int, const _ns1__GetStudyAreaSetupDateTimeResponse *, const char*);
SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTimeResponse * SOAP_FMAC4 soap_in__ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, const char*, _ns1__GetStudyAreaSetupDateTimeResponse *, const char*);

#define soap_write__ns1__GetStudyAreaSetupDateTimeResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetStudyAreaSetupDateTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetStudyAreaSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTimeResponse * SOAP_FMAC4 soap_get__ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, _ns1__GetStudyAreaSetupDateTimeResponse *, const char*, const char*);

#define soap_new__ns1__GetStudyAreaSetupDateTimeResponse(soap, n) soap_instantiate__ns1__GetStudyAreaSetupDateTimeResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetStudyAreaSetupDateTimeResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetStudyAreaSetupDateTimeResponse * SOAP_FMAC2 soap_instantiate__ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetStudyAreaSetupDateTime
#define SOAP_TYPE__ns1__GetStudyAreaSetupDateTime (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetStudyAreaSetupDateTime(struct soap*, const char*, int, const _ns1__GetStudyAreaSetupDateTime *, const char*);
SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_in__ns1__GetStudyAreaSetupDateTime(struct soap*, const char*, _ns1__GetStudyAreaSetupDateTime *, const char*);

#define soap_write__ns1__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_get__ns1__GetStudyAreaSetupDateTime(struct soap*, _ns1__GetStudyAreaSetupDateTime *, const char*, const char*);

#define soap_new__ns1__GetStudyAreaSetupDateTime(soap, n) soap_instantiate__ns1__GetStudyAreaSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetStudyAreaSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetStudyAreaSetupDateTime * SOAP_FMAC2 soap_instantiate__ns1__GetStudyAreaSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetStudyAreaSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetEnvisionVersionResponse
#define SOAP_TYPE__ns1__GetEnvisionVersionResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetEnvisionVersionResponse(struct soap*, const char*, int, const _ns1__GetEnvisionVersionResponse *, const char*);
SOAP_FMAC3 _ns1__GetEnvisionVersionResponse * SOAP_FMAC4 soap_in__ns1__GetEnvisionVersionResponse(struct soap*, const char*, _ns1__GetEnvisionVersionResponse *, const char*);

#define soap_write__ns1__GetEnvisionVersionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetEnvisionVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetEnvisionVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionVersionResponse * SOAP_FMAC4 soap_get__ns1__GetEnvisionVersionResponse(struct soap*, _ns1__GetEnvisionVersionResponse *, const char*, const char*);

#define soap_new__ns1__GetEnvisionVersionResponse(soap, n) soap_instantiate__ns1__GetEnvisionVersionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetEnvisionVersionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetEnvisionVersionResponse * SOAP_FMAC2 soap_instantiate__ns1__GetEnvisionVersionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetEnvisionVersionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetEnvisionVersion
#define SOAP_TYPE__ns1__GetEnvisionVersion (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetEnvisionVersion(struct soap*, const char*, int, const _ns1__GetEnvisionVersion *, const char*);
SOAP_FMAC3 _ns1__GetEnvisionVersion * SOAP_FMAC4 soap_in__ns1__GetEnvisionVersion(struct soap*, const char*, _ns1__GetEnvisionVersion *, const char*);

#define soap_write__ns1__GetEnvisionVersion(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetEnvisionVersion(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionVersion * SOAP_FMAC4 soap_get__ns1__GetEnvisionVersion(struct soap*, _ns1__GetEnvisionVersion *, const char*, const char*);

#define soap_new__ns1__GetEnvisionVersion(soap, n) soap_instantiate__ns1__GetEnvisionVersion(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetEnvisionVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetEnvisionVersion * SOAP_FMAC2 soap_instantiate__ns1__GetEnvisionVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetEnvisionVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetEnvisionSetupDateTimeResponse
#define SOAP_TYPE__ns1__GetEnvisionSetupDateTimeResponse (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetEnvisionSetupDateTimeResponse(struct soap*, const char*, int, const _ns1__GetEnvisionSetupDateTimeResponse *, const char*);
SOAP_FMAC3 _ns1__GetEnvisionSetupDateTimeResponse * SOAP_FMAC4 soap_in__ns1__GetEnvisionSetupDateTimeResponse(struct soap*, const char*, _ns1__GetEnvisionSetupDateTimeResponse *, const char*);

#define soap_write__ns1__GetEnvisionSetupDateTimeResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetEnvisionSetupDateTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetEnvisionSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionSetupDateTimeResponse * SOAP_FMAC4 soap_get__ns1__GetEnvisionSetupDateTimeResponse(struct soap*, _ns1__GetEnvisionSetupDateTimeResponse *, const char*, const char*);

#define soap_new__ns1__GetEnvisionSetupDateTimeResponse(soap, n) soap_instantiate__ns1__GetEnvisionSetupDateTimeResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetEnvisionSetupDateTimeResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetEnvisionSetupDateTimeResponse * SOAP_FMAC2 soap_instantiate__ns1__GetEnvisionSetupDateTimeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetEnvisionSetupDateTimeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetEnvisionSetupDateTime
#define SOAP_TYPE__ns1__GetEnvisionSetupDateTime (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetEnvisionSetupDateTime(struct soap*, const char*, int, const _ns1__GetEnvisionSetupDateTime *, const char*);
SOAP_FMAC3 _ns1__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_in__ns1__GetEnvisionSetupDateTime(struct soap*, const char*, _ns1__GetEnvisionSetupDateTime *, const char*);

#define soap_write__ns1__GetEnvisionSetupDateTime(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read__ns1__GetEnvisionSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_get__ns1__GetEnvisionSetupDateTime(struct soap*, _ns1__GetEnvisionSetupDateTime *, const char*, const char*);

#define soap_new__ns1__GetEnvisionSetupDateTime(soap, n) soap_instantiate__ns1__GetEnvisionSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetEnvisionSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetEnvisionSetupDateTime * SOAP_FMAC2 soap_instantiate__ns1__GetEnvisionSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetEnvisionSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns3__GetStudyAreaVersion
#define SOAP_TYPE___ns3__GetStudyAreaVersion (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetStudyAreaVersion(struct soap*, struct __ns3__GetStudyAreaVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetStudyAreaVersion(struct soap*, const struct __ns3__GetStudyAreaVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetStudyAreaVersion(struct soap*, const char*, int, const struct __ns3__GetStudyAreaVersion *, const char*);
SOAP_FMAC3 struct __ns3__GetStudyAreaVersion * SOAP_FMAC4 soap_in___ns3__GetStudyAreaVersion(struct soap*, const char*, struct __ns3__GetStudyAreaVersion *, const char*);

#define soap_write___ns3__GetStudyAreaVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__GetStudyAreaVersion(soap, data), 0) || soap_put___ns3__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetStudyAreaVersion(struct soap*, const struct __ns3__GetStudyAreaVersion *, const char*, const char*);

#define soap_read___ns3__GetStudyAreaVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns3__GetStudyAreaVersion * SOAP_FMAC4 soap_get___ns3__GetStudyAreaVersion(struct soap*, struct __ns3__GetStudyAreaVersion *, const char*, const char*);

#define soap_new___ns3__GetStudyAreaVersion(soap, n) soap_instantiate___ns3__GetStudyAreaVersion(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__GetStudyAreaVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__GetStudyAreaVersion * SOAP_FMAC2 soap_instantiate___ns3__GetStudyAreaVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetStudyAreaVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetStudyAreaSetupDateTime
#define SOAP_TYPE___ns3__GetStudyAreaSetupDateTime (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetStudyAreaSetupDateTime(struct soap*, struct __ns3__GetStudyAreaSetupDateTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetStudyAreaSetupDateTime(struct soap*, const struct __ns3__GetStudyAreaSetupDateTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetStudyAreaSetupDateTime(struct soap*, const char*, int, const struct __ns3__GetStudyAreaSetupDateTime *, const char*);
SOAP_FMAC3 struct __ns3__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_in___ns3__GetStudyAreaSetupDateTime(struct soap*, const char*, struct __ns3__GetStudyAreaSetupDateTime *, const char*);

#define soap_write___ns3__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__GetStudyAreaSetupDateTime(soap, data), 0) || soap_put___ns3__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetStudyAreaSetupDateTime(struct soap*, const struct __ns3__GetStudyAreaSetupDateTime *, const char*, const char*);

#define soap_read___ns3__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns3__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_get___ns3__GetStudyAreaSetupDateTime(struct soap*, struct __ns3__GetStudyAreaSetupDateTime *, const char*, const char*);

#define soap_new___ns3__GetStudyAreaSetupDateTime(soap, n) soap_instantiate___ns3__GetStudyAreaSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__GetStudyAreaSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__GetStudyAreaSetupDateTime * SOAP_FMAC2 soap_instantiate___ns3__GetStudyAreaSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetStudyAreaSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetEnvisionVersion
#define SOAP_TYPE___ns3__GetEnvisionVersion (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetEnvisionVersion(struct soap*, struct __ns3__GetEnvisionVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetEnvisionVersion(struct soap*, const struct __ns3__GetEnvisionVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetEnvisionVersion(struct soap*, const char*, int, const struct __ns3__GetEnvisionVersion *, const char*);
SOAP_FMAC3 struct __ns3__GetEnvisionVersion * SOAP_FMAC4 soap_in___ns3__GetEnvisionVersion(struct soap*, const char*, struct __ns3__GetEnvisionVersion *, const char*);

#define soap_write___ns3__GetEnvisionVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__GetEnvisionVersion(soap, data), 0) || soap_put___ns3__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetEnvisionVersion(struct soap*, const struct __ns3__GetEnvisionVersion *, const char*, const char*);

#define soap_read___ns3__GetEnvisionVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns3__GetEnvisionVersion * SOAP_FMAC4 soap_get___ns3__GetEnvisionVersion(struct soap*, struct __ns3__GetEnvisionVersion *, const char*, const char*);

#define soap_new___ns3__GetEnvisionVersion(soap, n) soap_instantiate___ns3__GetEnvisionVersion(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__GetEnvisionVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__GetEnvisionVersion * SOAP_FMAC2 soap_instantiate___ns3__GetEnvisionVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetEnvisionVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns3__GetEnvisionSetupDateTime
#define SOAP_TYPE___ns3__GetEnvisionSetupDateTime (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetEnvisionSetupDateTime(struct soap*, struct __ns3__GetEnvisionSetupDateTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetEnvisionSetupDateTime(struct soap*, const struct __ns3__GetEnvisionSetupDateTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetEnvisionSetupDateTime(struct soap*, const char*, int, const struct __ns3__GetEnvisionSetupDateTime *, const char*);
SOAP_FMAC3 struct __ns3__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_in___ns3__GetEnvisionSetupDateTime(struct soap*, const char*, struct __ns3__GetEnvisionSetupDateTime *, const char*);

#define soap_write___ns3__GetEnvisionSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__GetEnvisionSetupDateTime(soap, data), 0) || soap_put___ns3__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetEnvisionSetupDateTime(struct soap*, const struct __ns3__GetEnvisionSetupDateTime *, const char*, const char*);

#define soap_read___ns3__GetEnvisionSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns3__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_get___ns3__GetEnvisionSetupDateTime(struct soap*, struct __ns3__GetEnvisionSetupDateTime *, const char*, const char*);

#define soap_new___ns3__GetEnvisionSetupDateTime(soap, n) soap_instantiate___ns3__GetEnvisionSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__GetEnvisionSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns3__GetEnvisionSetupDateTime * SOAP_FMAC2 soap_instantiate___ns3__GetEnvisionSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__GetEnvisionSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__GetStudyAreaVersion
#define SOAP_TYPE___ns2__GetStudyAreaVersion (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__GetStudyAreaVersion(struct soap*, struct __ns2__GetStudyAreaVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__GetStudyAreaVersion(struct soap*, const struct __ns2__GetStudyAreaVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__GetStudyAreaVersion(struct soap*, const char*, int, const struct __ns2__GetStudyAreaVersion *, const char*);
SOAP_FMAC3 struct __ns2__GetStudyAreaVersion * SOAP_FMAC4 soap_in___ns2__GetStudyAreaVersion(struct soap*, const char*, struct __ns2__GetStudyAreaVersion *, const char*);

#define soap_write___ns2__GetStudyAreaVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__GetStudyAreaVersion(soap, data), 0) || soap_put___ns2__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__GetStudyAreaVersion(struct soap*, const struct __ns2__GetStudyAreaVersion *, const char*, const char*);

#define soap_read___ns2__GetStudyAreaVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__GetStudyAreaVersion * SOAP_FMAC4 soap_get___ns2__GetStudyAreaVersion(struct soap*, struct __ns2__GetStudyAreaVersion *, const char*, const char*);

#define soap_new___ns2__GetStudyAreaVersion(soap, n) soap_instantiate___ns2__GetStudyAreaVersion(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__GetStudyAreaVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__GetStudyAreaVersion * SOAP_FMAC2 soap_instantiate___ns2__GetStudyAreaVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__GetStudyAreaVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__GetStudyAreaSetupDateTime
#define SOAP_TYPE___ns2__GetStudyAreaSetupDateTime (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__GetStudyAreaSetupDateTime(struct soap*, struct __ns2__GetStudyAreaSetupDateTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__GetStudyAreaSetupDateTime(struct soap*, const struct __ns2__GetStudyAreaSetupDateTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__GetStudyAreaSetupDateTime(struct soap*, const char*, int, const struct __ns2__GetStudyAreaSetupDateTime *, const char*);
SOAP_FMAC3 struct __ns2__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_in___ns2__GetStudyAreaSetupDateTime(struct soap*, const char*, struct __ns2__GetStudyAreaSetupDateTime *, const char*);

#define soap_write___ns2__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__GetStudyAreaSetupDateTime(soap, data), 0) || soap_put___ns2__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__GetStudyAreaSetupDateTime(struct soap*, const struct __ns2__GetStudyAreaSetupDateTime *, const char*, const char*);

#define soap_read___ns2__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__GetStudyAreaSetupDateTime * SOAP_FMAC4 soap_get___ns2__GetStudyAreaSetupDateTime(struct soap*, struct __ns2__GetStudyAreaSetupDateTime *, const char*, const char*);

#define soap_new___ns2__GetStudyAreaSetupDateTime(soap, n) soap_instantiate___ns2__GetStudyAreaSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__GetStudyAreaSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__GetStudyAreaSetupDateTime * SOAP_FMAC2 soap_instantiate___ns2__GetStudyAreaSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__GetStudyAreaSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__GetEnvisionVersion
#define SOAP_TYPE___ns2__GetEnvisionVersion (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__GetEnvisionVersion(struct soap*, struct __ns2__GetEnvisionVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__GetEnvisionVersion(struct soap*, const struct __ns2__GetEnvisionVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__GetEnvisionVersion(struct soap*, const char*, int, const struct __ns2__GetEnvisionVersion *, const char*);
SOAP_FMAC3 struct __ns2__GetEnvisionVersion * SOAP_FMAC4 soap_in___ns2__GetEnvisionVersion(struct soap*, const char*, struct __ns2__GetEnvisionVersion *, const char*);

#define soap_write___ns2__GetEnvisionVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__GetEnvisionVersion(soap, data), 0) || soap_put___ns2__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__GetEnvisionVersion(struct soap*, const struct __ns2__GetEnvisionVersion *, const char*, const char*);

#define soap_read___ns2__GetEnvisionVersion(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__GetEnvisionVersion * SOAP_FMAC4 soap_get___ns2__GetEnvisionVersion(struct soap*, struct __ns2__GetEnvisionVersion *, const char*, const char*);

#define soap_new___ns2__GetEnvisionVersion(soap, n) soap_instantiate___ns2__GetEnvisionVersion(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__GetEnvisionVersion(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__GetEnvisionVersion * SOAP_FMAC2 soap_instantiate___ns2__GetEnvisionVersion(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__GetEnvisionVersion(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns2__GetEnvisionSetupDateTime
#define SOAP_TYPE___ns2__GetEnvisionSetupDateTime (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__GetEnvisionSetupDateTime(struct soap*, struct __ns2__GetEnvisionSetupDateTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__GetEnvisionSetupDateTime(struct soap*, const struct __ns2__GetEnvisionSetupDateTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__GetEnvisionSetupDateTime(struct soap*, const char*, int, const struct __ns2__GetEnvisionSetupDateTime *, const char*);
SOAP_FMAC3 struct __ns2__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_in___ns2__GetEnvisionSetupDateTime(struct soap*, const char*, struct __ns2__GetEnvisionSetupDateTime *, const char*);

#define soap_write___ns2__GetEnvisionSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__GetEnvisionSetupDateTime(soap, data), 0) || soap_put___ns2__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__GetEnvisionSetupDateTime(struct soap*, const struct __ns2__GetEnvisionSetupDateTime *, const char*, const char*);

#define soap_read___ns2__GetEnvisionSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns2__GetEnvisionSetupDateTime * SOAP_FMAC4 soap_get___ns2__GetEnvisionSetupDateTime(struct soap*, struct __ns2__GetEnvisionSetupDateTime *, const char*, const char*);

#define soap_new___ns2__GetEnvisionSetupDateTime(soap, n) soap_instantiate___ns2__GetEnvisionSetupDateTime(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__GetEnvisionSetupDateTime(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns2__GetEnvisionSetupDateTime * SOAP_FMAC2 soap_instantiate___ns2__GetEnvisionSetupDateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__GetEnvisionSetupDateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetStudyAreaVersionResponse
#define SOAP_TYPE_PointerTo_ns1__GetStudyAreaVersionResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetStudyAreaVersionResponse(struct soap*, _ns1__GetStudyAreaVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetStudyAreaVersionResponse(struct soap*, const char *, int, _ns1__GetStudyAreaVersionResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetStudyAreaVersionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetStudyAreaVersionResponse(struct soap*, const char*, _ns1__GetStudyAreaVersionResponse **, const char*);

#define soap_write_PointerTo_ns1__GetStudyAreaVersionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetStudyAreaVersionResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetStudyAreaVersionResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetStudyAreaVersionResponse(struct soap*, _ns1__GetStudyAreaVersionResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetStudyAreaVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetStudyAreaVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaVersionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetStudyAreaVersionResponse(struct soap*, _ns1__GetStudyAreaVersionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetStudyAreaVersion
#define SOAP_TYPE_PointerTo_ns1__GetStudyAreaVersion (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetStudyAreaVersion(struct soap*, _ns1__GetStudyAreaVersion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetStudyAreaVersion(struct soap*, const char *, int, _ns1__GetStudyAreaVersion *const*, const char *);
SOAP_FMAC3 _ns1__GetStudyAreaVersion ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetStudyAreaVersion(struct soap*, const char*, _ns1__GetStudyAreaVersion **, const char*);

#define soap_write_PointerTo_ns1__GetStudyAreaVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetStudyAreaVersion(soap, data), 0) || soap_put_PointerTo_ns1__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetStudyAreaVersion(struct soap*, _ns1__GetStudyAreaVersion *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetStudyAreaVersion(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetStudyAreaVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaVersion ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetStudyAreaVersion(struct soap*, _ns1__GetStudyAreaVersion **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse
#define SOAP_TYPE_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, _ns1__GetStudyAreaSetupDateTimeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, const char *, int, _ns1__GetStudyAreaSetupDateTimeResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTimeResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, const char*, _ns1__GetStudyAreaSetupDateTimeResponse **, const char*);

#define soap_write_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, _ns1__GetStudyAreaSetupDateTimeResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTimeResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetStudyAreaSetupDateTimeResponse(struct soap*, _ns1__GetStudyAreaSetupDateTimeResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetStudyAreaSetupDateTime
#define SOAP_TYPE_PointerTo_ns1__GetStudyAreaSetupDateTime (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetStudyAreaSetupDateTime(struct soap*, _ns1__GetStudyAreaSetupDateTime *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetStudyAreaSetupDateTime(struct soap*, const char *, int, _ns1__GetStudyAreaSetupDateTime *const*, const char *);
SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTime ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetStudyAreaSetupDateTime(struct soap*, const char*, _ns1__GetStudyAreaSetupDateTime **, const char*);

#define soap_write_PointerTo_ns1__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetStudyAreaSetupDateTime(soap, data), 0) || soap_put_PointerTo_ns1__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetStudyAreaSetupDateTime(struct soap*, _ns1__GetStudyAreaSetupDateTime *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetStudyAreaSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetStudyAreaSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetStudyAreaSetupDateTime ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetStudyAreaSetupDateTime(struct soap*, _ns1__GetStudyAreaSetupDateTime **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetEnvisionVersionResponse
#define SOAP_TYPE_PointerTo_ns1__GetEnvisionVersionResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetEnvisionVersionResponse(struct soap*, _ns1__GetEnvisionVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetEnvisionVersionResponse(struct soap*, const char *, int, _ns1__GetEnvisionVersionResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetEnvisionVersionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetEnvisionVersionResponse(struct soap*, const char*, _ns1__GetEnvisionVersionResponse **, const char*);

#define soap_write_PointerTo_ns1__GetEnvisionVersionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetEnvisionVersionResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetEnvisionVersionResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetEnvisionVersionResponse(struct soap*, _ns1__GetEnvisionVersionResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetEnvisionVersionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetEnvisionVersionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionVersionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetEnvisionVersionResponse(struct soap*, _ns1__GetEnvisionVersionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetEnvisionVersion
#define SOAP_TYPE_PointerTo_ns1__GetEnvisionVersion (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetEnvisionVersion(struct soap*, _ns1__GetEnvisionVersion *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetEnvisionVersion(struct soap*, const char *, int, _ns1__GetEnvisionVersion *const*, const char *);
SOAP_FMAC3 _ns1__GetEnvisionVersion ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetEnvisionVersion(struct soap*, const char*, _ns1__GetEnvisionVersion **, const char*);

#define soap_write_PointerTo_ns1__GetEnvisionVersion(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetEnvisionVersion(soap, data), 0) || soap_put_PointerTo_ns1__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetEnvisionVersion(struct soap*, _ns1__GetEnvisionVersion *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetEnvisionVersion(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetEnvisionVersion(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionVersion ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetEnvisionVersion(struct soap*, _ns1__GetEnvisionVersion **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetEnvisionSetupDateTimeResponse
#define SOAP_TYPE_PointerTo_ns1__GetEnvisionSetupDateTimeResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(struct soap*, _ns1__GetEnvisionSetupDateTimeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(struct soap*, const char *, int, _ns1__GetEnvisionSetupDateTimeResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetEnvisionSetupDateTimeResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(struct soap*, const char*, _ns1__GetEnvisionSetupDateTimeResponse **, const char*);

#define soap_write_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(struct soap*, _ns1__GetEnvisionSetupDateTimeResponse *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionSetupDateTimeResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetEnvisionSetupDateTimeResponse(struct soap*, _ns1__GetEnvisionSetupDateTimeResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetEnvisionSetupDateTime
#define SOAP_TYPE_PointerTo_ns1__GetEnvisionSetupDateTime (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetEnvisionSetupDateTime(struct soap*, _ns1__GetEnvisionSetupDateTime *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetEnvisionSetupDateTime(struct soap*, const char *, int, _ns1__GetEnvisionSetupDateTime *const*, const char *);
SOAP_FMAC3 _ns1__GetEnvisionSetupDateTime ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetEnvisionSetupDateTime(struct soap*, const char*, _ns1__GetEnvisionSetupDateTime **, const char*);

#define soap_write_PointerTo_ns1__GetEnvisionSetupDateTime(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetEnvisionSetupDateTime(soap, data), 0) || soap_put_PointerTo_ns1__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetEnvisionSetupDateTime(struct soap*, _ns1__GetEnvisionSetupDateTime *const*, const char*, const char*);

#define soap_read_PointerTo_ns1__GetEnvisionSetupDateTime(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetEnvisionSetupDateTime(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 _ns1__GetEnvisionSetupDateTime ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetEnvisionSetupDateTime(struct soap*, _ns1__GetEnvisionSetupDateTime **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
