//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EnvWinLibs.rc
//
#define IDC_LIB_CAPTION                 101
#define IDC_LIB_TITLE                   102
#define IDC_LIB_XAXIS                   103
#define IDC_LIB_YAXIS                   104
#define IDC_LIB_SHOWHORZ                105
#define IDC_LIB_SHOWVERT                106
#define IDC_LIB_GROOVED                 107
#define IDC_LIB_RAISED                  108
#define IDC_LIB_SUNKEN                  109
#define IDC_LIB_LINE                    110
#define IDC_LIB_LINELABEL               111
#define IDC_LIB_SCALEMIN                112
#define IDC_LIB_LINECOLOR               113
#define IDC_LIB_LINESTYLE               114
#define IDC_LIB_SCALEMAX                115
#define IDC_LIB_LINEWIDTH               116
#define IDC_LIB_AUTOSCALE               117
#define IDC_LIB_MARKER                  118
#define IDC_LIB_MARKERINCR              119
#define IDC_LIB_SHOWLINE                120
#define IDC_LIB_SHOWMARKER              121
#define IDC_LIB_TICMAJOR                122
#define IDC_LIB_MARKERINCR2             122
#define IDC_LIB_LEGENDHEIGHT            122
#define IDC_LIB_TICMINOR                123
#define IDC_LIB_SMOOTH                  123
#define IDC_LIB_AUTOINCR                124
#define IDC_LIB_LEGENDHEIGHT2           124
#define IDC_LIB_TENSION                 124
#define IDC_LIB_TICDECIMALS             125
#define IDC_LIB_GLOBAL                  126
#define IDC_LIB_LOCAL                   127
#define IDC_LIB_TICMAJORLABEL           128
#define IDC_LIB_TICMINORLABEL           129
#define IDC_LIB_SCALEMINLABEL           130
#define IDC_LIB_SCALEMAXLABEL           131
#define IDC_LIB_AXIS                    132
#define IDC_LIB_LINEFONT                133
#define IDD_LIB_S3D_DATA_SET_PROPS      136
#define IDD_LIB_MAPLAYERPROPS           137
#define IDC_LIB_LAYER                   138
#define IDC_LIB_QUERY                   170
#define IDC_LIB_ADD                     177
#define IDC_LIB_DESCRIPTION             178
#define IDC_LIB_AND                     186
#define IDC_LIB_OR                      187
#define IDC_LIB_CLEARPREV               190
#define IDD_LIB_QUERY                   212
#define IDC_LIB_DATA_SET_COMBO          1000
#define IDC_LIB_POINT_SIZE_COMBO        1001
#define IDC_LIB_POINT_TYPE_COMBO        1002
#define IDC_LIB_POINT_SIZE_COMBO2       1003
#define IDC_LIB_LINE_SIZE_COMBO         1003
#define IDC_LIB_COLOR_STATIC            1004
#define IDC_LIB_COLOR_STATIC_LINES      1005
#define IDC_LIB_PREVIEW_STATIC          1006
#define IDC_LIB_LFILE                   1007
#define IDC_LIB_SET_COLOR_BUTTON        1008
#define IDC_LIB_SET_COLOR_BUTTON_LINES  1009
#define IDC_LIB_UPDATEPLOT              1010
#define IDC_LIB_LTYPE                   1011
#define IDC_LIB_FEATURES                1012
#define IDC_LIB_SHOWOUTLINES            1013
#define IDC_LIB_INTENSITY               1014
#define IDC_LIB_INTENSITYTEXT           1015
#define IDC_LIB_LIGHTER                 1016
#define IDC_LIB_DARKER                  1017
#define IDC_LIB_VISIBLE                 1062
#define IDC_LIB_OUTLINECOLOR            1089
#define IDC_LIB_HATCHCOLOR              1092
#define IDC_LIB_FIELDS                  1127
#define IDC_LIB_OPS                     1128
#define IDC_LIB_VALUES                  1129
#define IDC_LIB_HATCHPATTERN            1161
#define IDD_LIB_QUERYBUILDER            2000
#define IDC_LIB_QBFIELDS                2001
#define IDC_LIB_QBOPERATORS             2002
#define IDC_LIB_QBVALUES                2003
#define IDC_LIB_QBDESCRIPTION           2004
#define IDC_LIB_QBADD                   2005
#define IDC_LIB_QBAND                   2006
#define IDC_LIB_QBOR                    2007
#define IDC_LIB_QBSPATIALOPS            2008
#define IDC_LIB_QBRUNGLOBAL             2009
#define IDC_LIB_QBCLEARPREV             2010
#define IDC_LIB_QBQUERYVIEWER           2011
#define IDC_LIB_QBQUERY                 2012
#define IDC_LIB_QBHISTORY               2013
#define IDC_LIB_QBLAYER                 2014
#define IDC_LIB_QBRUN                   2015
#define IDC_DEBUGINFO                   2057
#define IDD_LIB_SPATIALOPERATORS        2100
#define IDC_LIB_NEXTTO                  2101
#define IDC_LIB_NEXTTOAREA              2102
#define IDC_LIB_WITHIN                  2103
#define IDC_LIB_WITHINAREA              2104
#define IDC_LIB_COMMENT                 2105
#define IDC_LIB_DISTANCELABEL           2106
#define IDC_LIB_DISTANCE                2107
#define IDC_LIB_AREA                    2108
#define IDC_LIB_AREALABEL               2109
#define IDD_LIB_QUERYVIEWER             2200
#define IDC_LIB_QVQUERY                 2201
#define IDC_LIB_QVTREE                  2202
#define IDD_LIB_PLOTSETUP               3001
#define IDD_LIB_PLOTAXES                3002
#define IDD_LIB_PLOTLINES               3003
#define IDC_LIB_FONTCAPTION             3006
#define IDC_LIB_FONTTITLE               3007
#define IDC_LIB_FONTXAXIS               3008
#define IDC_LIB_FONTYAXIS               3009
#define IDC_LIB_VARWIDTH                3012
#define IDC_LIB_LEDITFIELDINFO          3013
#define IDC_LIB_LWIDTH                  3014
#define IDC_LIB_LSPIN1                  3016
#define IDD_LIB_MAPLABELS               3017
#define IDC_LIB_LLAYERS                 3017
#define IDC_LIB_SHOWLABELS              3018
#define IDC_LIB_LABEL_FIELDS            3019
#define IDD_LIB_NAME                    3019
#define IDC_LIB_FONTSAMPLE              3020
#define IDD_LIB_CELLPROPERTIES          3020
#define IDC_LIB_SETFONT                 3021
#define IDD_LIB_ERRORREPORT             3021
#define IDD_LIB_SORTCOLS                3023
#define IDC_LIB_EDITLABELINFO           3024
#define IDC_LIB_FIELDCOMBO              3026
#define IDC_LIB_ADDFIELD                3027
#define IDC_LIB_REMOVEFIELD             3028
#define IDC_LIB_TYPE                    3029
#define IDC_LIB_WIDTH                   3030
#define IDC_LIB_DECIMALS                3031
#define IDC_LIB_REORDERCOLS             3032
#define IDC_LIB_EXTENTS2                3033
#define IDC_LIB_NAME                    3034
#define IDC_LIB_FLASHCELL               3035
#define IDC_LIB_NEXTCELL                3036
#define IDC_LIB_PREVCELL                3037
#define IDC_LIB_GRID_FRAME              3038
#define IDC_LIB_TRANSPARENCY            3040
#define IDC_LIB_TRANSPARENCY_VALUE      3041
#define ID_LIB_CELLPROPERTIES           3042
#define ID_LIB_SHOWSAMEATTRIBUTE        3043
#define ID_LIB_SHOWPOLYGONVERTICES      3044
#define ID_LIB_ZOOMTOPOLY               3045
#define ID_LIB_RECLASSIFYDATA           3046
#define IDC_LIB_MSG                     3047
#define IDC_LIB_OUTPUT                  3048
#define IDC_LIB_NOMSGS                  3049
#define IDC_LIB_TENSIONLABEL            3052
#define IDC_LIB_TOTALAREA               3054
#define IDC_LIB_AVERAGEAREA             3055
#define IDC_LIB_AREARANGE               3056
#define IDC_LIB_AVERAGEAREA2            3056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2025
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2058
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
