//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Envision.rc
//
#define IDC_NEWPROJECT                  2
#define IDOK3                           2
#define IDC_OPEN                        3
#define IDOK2                           3
#define IDC_EXTRACT                     3
#define IDC_EXTRACT2                    4
#define IDC_LOADFROMFILE                4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_NEWINI_STEP1                107
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_EnvisionTYPE                130
#define IDC_LIST                        139
#define IDC_SIDE                        140
#define IDC_LIGHTBULB                   141
#define IDB_LIGHTBULB                   142
#define IDC_NEXTTIP                     146
#define IDC_STARTUP                     147
#define IDC_TIPSTRING                   148
#define IDC_PREVTIP                     149
#define IDC_HEADER                      150
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDC_FLASHCELL                   180
#define IDC_PREVCELL                    181
#define IDC_NEXTCELL                    182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_SELECTWATERSHED              242
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define ID_STATUSBAR_PROGRESSBAR        300
#define IDC_REPLACE                     300
#define ID_STATUSBAR_MULTIRUNPROGRESSBAR 301
#define ID_STATUSBAR_ZOOMBUTTON         302
#define ID_STATUSBAR_ZOOMSLIDER         303
#define IDS_EDIT_MENU                   306
#define ID_VIEW_OUTPUTWND               309
#define ID_ADD_SUBMENU                  310
#define IDD_DATAPANEL                   311
#define IDB_MAPLARGE                    314
#define IDB_BITMAP4                     315
#define IDB_MAPSMALL                    315
#define IDB_DATASMALL                   316
#define IDB_DATALARGE                   317
#define IDB_ANALYSIS_SMALL              318
#define IDB_ANALYSIS_LARGE              319
#define ID_WRITE_PASTEASHYPERLINK       320
#define ID_ZOOMIN                       321
#define ID_ZOOMOUT                      322
#define ID_FILE_LOADMAP                 323
#define ID_FILE_LOADRULES               324
#define ID_CLEAR_SELECTION              325
#define ID_SELECT                       326
#define ID_ZOOMFULL                     327
#define ID_ZOOMTOQUERY                  328
#define ID_QUERYDISTANCE                329
#define ID_TABLE                        330
#define ID_DBTABLE                      331
#define ID_PAN                          332
#define ID_MAPCONTEXTMENU_CLEARALTERNATIVES 334
#define ID_CLEARALTERNATIVES            335
#define ID_MAPCONTEXTMENU_SELECTWATERSHED 336
#define ID_MAPCONTEXTMENU_RECLASSIFY    337
#define ID_WINDOW_TILE                  338
#define ID_EVALUATE_SOCIOECONOMICS      339
#define ID_VIEW_POLYGONEDGES            340
#define ID_VIEW_SHOWSCALE               341
#define ID_VIEW_SHOWATTRIBUTE           342
#define ID_ANALYSIS_SHOWACTORTERRITORY  343
#define ID_ANALYSIS_SHOWPOLICYMAP       344
#define ID_ANALYSIS_SHOWACTORS          345
#define ID_DATA_LULCINFO                346
#define ID_EVALUATE                     347
#define ID_FILE_RESET                   348
#define ID_DATA_EXPORTDATA              349
#define ID_ANALYSIS_STOP                350
#define ID_ANALYSIS_RESET               351
#define ID_INTERACTIVE_HOSTINTERACTIVESESSION 352
#define ID_INTERACTIVE_CONNECTTOHOST    353
#define ID_ANALYSIS_SHOWDELTALIST       354
#define ID_ANALYSIS_SETUPPOLICYMETAPROCESS 355
#define ID_DATA_LOADRUNDATA             356
#define ID_DATA_STORERUNDATA            357
#define ID_RESULT_TABLE                 360
#define ID_RESULT_MAP                   361
#define ID_RESULT_GRAPH                 362
#define ID_VIEW_ADDNEWVIEW              363
#define ID_ADDNEWVIEW_MAPLAYER          364
#define ID_ADDNEWVIEW_GRAPH             365
#define ID_ADDNEWVIEW_TABLE             366
#define ID_FILE_SAVEDATABASE            367
#define ID_SAVE_SHAPEFILE               368
#define ID_EXPORT_ACTORS                370
#define ID_EXPORT_POLICIES              371
#define ID_EXPORT_POLICIESASHTML        372
#define ID_EXPORT_FIELDINFOASHTML       373
#define ID_EXPORT_LULC                  374
#define ID_EXPORT_SCENARIOS             375
#define ID_EXPORT_FIELDINFO             376
#define ID_FILE_IMPORT                  380
#define ID_IMPORT_POLICIES              381
#define ID_IMPORT_ACTORS                382
#define ID_IMPORT_LULC                  383
#define ID_IMPORT_SCENARIOS             384
#define ID_IMPORT_MULTIRUNDATASETS      385
#define ID_FILE_EXPORT                  386
#define ID_DATA_CHANGETYPE              399
#define ID_DATA_MERGE                   400
#define ID_DATA_ADDCOL                  401
#define IDC_LOAD                        401
#define ID_DATA_REMOVECOL               402
#define IDC_SAVE                        402
#define ID_DATA_CALCULATEFIELD          403
#define ID_DATA_LULC_FIELDS             404
#define IDD_PPVEGDATA                   404
#define ID_DATA_DISTANCETO              405
#define IDD_RUNPOLICY                   405
#define ID_DATA_ADJACENTTO              406
#define ID_DATA_AREA                    407
#define ID_DATA_ELEVATION               408
#define ID_DATA_LINEARDENSITY           409
#define ID_DATA_TEXT_TO_ID              410
#define ID_DATA_INTERSECT               411
#define ID_DATA_RECLASS                 412
#define ID_DATA_IDUINDEX                413
#define ID_DATA_PROJECT3D               414
#define ID_DATA_BUILDNETWORKTREE        415
#define ID_DATA_IDUINFO                 416
#define ID_DATA_IDUDOC                  417
#define ID_DATA_VERIFYCELLLAYER         418
#define ID_DATA_EVALUATIVEMODELLEARNING 419
#define ID_DATA_INITIALIZEPOLICYEFFICACIES 420
#define ID_DATA_HISTOGRAM               421

#define ID_EDIT_POLICIES                423
#define ID_EDIT_ACTORS                  424
#define ID_EDIT_LULC                    425
#define ID_EDIT_SCENARIOS               426
#define ID_ANALYSIS_SETUP_RUN           430
#define ID_ANALYSIS_SETUP_MODELS        431
#define ID_ANALYSIS_RUN                 432
#define ID_ANALYSIS_RUNMULTIPLE         433
#define ID_ANALYSIS_STARTYEAR           434
#define ID_ANALYSIS_STOPTIME            435
#define ID_ANALYSIS_EXPORTCOVERAGES     436
#define ID_ANALYSIS_EXPORTINTERVAL      437
#define ID_ANALYSIS_EXPORTOUTPUTS       438
#define ID_ANALYSIS_EXPORTDELTAS        439
#define ID_ANALYSIS_EXPORTDELTAFIELDS   440
#define ID_ANALYSIS_VIDEORECORDERS      441
#define ID_ANALYSIS_SENSITIVITY         442
#define ID_EDIT_SETPOLICYCOLORS         444
#define ID_EDIT_FIELDINFO               445
#define ID_MAP_AREASUMMARY              446
#define ID_MAP_DOTDENSITYMAP            447
#define ID_MAP_CONVERT                  448
#define ID_MAPCONTEXTMENU_SHOWPOLYGONVERTICES 450
#define IDC_EDITABOUT                   451
#define ID_EDIT_INIFILE                 455
#define ID_EDIT_EDITSCENARIOS           460
#define ID_EDIT_COPYLEGEND              461
#define ID_VIEW_INPUT                   470
#define ID_VIEW_MAP                     471
#define ID_VIEW_TABLE                   472
#define ID_VIEW_3D                      473
#define ID_VIEW_RTVIEWS                 474
#define ID_VIEW_RESULTS                 475
#define ID_VIEW_OUTPUT                  476
#define ID_VIEW_ANALYTICS               477
#define ID_OPTIONS                      478
#define ID_EXPORT_MODELOUTPUTS          480
#define ID_EXPORT_MULTIRUNDATASETS      481
#define ID_EXPORT_DECADALCELLLAYERS     482
#define ID_EXPORT_DELTAARRAY            483
#define ID_RESULTS_TILE                 490
#define ID_RESULTS_CASCADE              491
#define ID_RESULTS_CAPTURE              492
#define ID_RESULTS_SYNC_MAPS            493
#define ID_RESULTS_CLEAR                494
#define ID_RESULTS_DELTAS               495
#define ID_RTVIEW_MAPS                  500
#define ID_RTVIEW_GRAPHS                501
#define ID_RTVIEW_VIEWS                 502
#define ID_RTVIEW_VISUALIZERS           503
#define ID_RTVIEW_TILE                  505
#define ID_RTVIEW_CASCADE               506
#define ID_RTVIEW_CLOSE                 507
#define ID_RTVIEW_REWIND                508
#define ID_RTVIEW_START                 509
#define ID_RTVIEW_PAUSE                 510
#define IDD_POLICYAPPPLOT               510
#define IDD_SANDBOXDLG                  511
#define IDD_SELECTIDU                   512
#define ID_HELP_UPDATEENVISION          512
#define IDD_EVAL_MODEL_LEARN_DLG_REPORT 513
#define ID_MAPCONTEXTMENU_ZOOMTOTHISPOLYGON 514
#define ID_ANALYTICS_TILE               520
#define IDC_SCOREFRAME                  520
#define ID_ANALYTICS_CASCADE            521
#define IDC_DELIMITERCOMBO              521
#define ID_ANALYTICS_CAPTURE            522
#define IDC_SCOREFRAME2                 522
#define ID_ANALYTICS_ADD                523
#define IDC_MODFRAME                    523
#define ID_ANALYTICS_CLEAR              524
#define IDC_MODELS                      524
#define IDC_RESULTS                     525
#define IDS_MULTIRUNPROGRESS            526
#define IDC_EXPORT                      527
#define IDC_STATICBOX                   528
#define IDR_MAPTOOLBAR                  529
#define IDC_MESSAGES                    530
#define IDR_MAPCONTEXTMENU              531
#define IDC_PORT                        532
#define IDC_PINSERVER                   533
#define IDC_APS                         534
#define IDC_PINGSERVER                  535
#define IDC_NAME                        536
#define IDI_MAPTEMP                     537
#define IDI_MAPTEMP1                    538
#define IDC_NAME2                       539
#define IDC_HOSTIP                      540
#define IDI_MAPLANDCOVER                541
#define IDC_NAME3                       542
#define IDC_MESSAGE                     543
#define IDI_MAPTEMP2                    544
#define IDC_CONNECT                     545
#define IDI_PLAY                        546
#define IDD_CLASSIFYLAYER               547
#define IDC_MULTIRUN                    548
#define IDI_RESTART                     549
#define IDC_ITERATIONSLABEL             550
#define IDI_STOP                        551
#define IDC_LISTVIEW                    552
#define IDI_LOGERROR                    553
#define IDI_LOGWARNING                  554
#define IDI_LOGINFO                     555
#define IDD_SAVECOLS                    556
#define IDD_RUN                         557
#define IDD_POLICYRESULTS               558
#define IDD_OBJECTIVESCORES             559
#define IDC_PDD_FROMLAYER               560
#define IDC_PDD_TARGETLAYER             561
#define IDB_CHECK                       562
#define IDC_PDD_TOLAYER                 563
#define IDC_PDD_SOURCELAYER             564
#define IDB_NEXT                        565
#define IDC_PDD_TOFIELD                 566
#define IDC_PDD_TARGETFIELD             567
#define IDB_PREVIOUS                    568
#define IDC_PDD_CALCULATE               570
#define IDC_PMP_PROGRRESS               571
#define IDC_PDD_INDEXFIELD              572
#define IDD_RESOPTIONS_ALTERNATIVES     573
#define IDC_PDD_VALUEFIELD              573
#define IDD_RUNSETUP                    574
#define IDC_PDD_VALUEFIELD2             574
#define IDC_PDD_SOURCEVALUEFIELD        574
#define IDC_EDITACTORDB                 575
#define IDC_EDITACTORDB2                576
#define IDD_DIALOGBAR                   577
#define IDD_OBJECTIVESCORESDETAIL       578
#define IDD_OBJECTIVESCORESSUMMARY      579
#define IDD_VIEW3D                      580
#define IDD_SELECTACTOR                 581
#define IDC_ACTORPOLICY                 582
#define IDC_NEXTTO                      583
#define IDC_LEVEL0                      584
#define IDC_ENVDB                       585
#define IDC_BUFFER                      586
#define IDC_USEDEFAULTVALUE             587
#define IDD_ACTOR                       588
#define IDC_WITHIN                      589
#define IDC_ADDPOINT                    590
#define IDD_RUNPOLICIES                 591
#define IDC_SCHEDULEDDATE               592
#define IDC_WITHINAREA                  593
#define IDC_STARTDATE                   594
#define IDC_INCREMENT                   595
#define IDC_SCHEDULEDDATELABEL          596
#define IDC_ENDDATE                     597
#define IDC_NEXTTOAREA                  598
#define IDC_PATH                        599
#define IDC_QUERYTARGET                 600
#define IDD_POLICYBASIC                 601
#define IDC_EDITSITECONSTRAINTS         602
#define IDC_RECORDS                     603
#define IDC_PERSISTPERIOD               604
#define IDD_POLICYSCORES                605
#define IDC_EDITSITECONSTRAINTS2        606
#define IDC_EDITOUTCOMES                607
#define IDC_DELAYPERIOD                 608
#define IDC_OTHER                       609
#define IDC_LULC                        610
#define IDC_LULC2                       611
#define IDC_EVALMODEL                   612
#define IDC_ADD                         613
#define IDC_EVALMODEL2                  614
#define IDC_AUTOPROCESS                 615
#define IDC_DESCRIPTION                 616
#define IDC_SELECTSITES                 617
#define IDC_USEINITIALSEED              618
#define IDC_ADD2                        619
#define IDC_EDIT                        620
#define IDC_ADDNEW                      621
#define IDC_SPATIALOPS                  622
#define IDC_FUNCTIONDESCRIPTION         623
#define IDD_RUNDATA                     624
#define IDD_LULCINFO                    625
#define IDC_NARRATIVE                   626
#define IDD_RUNACTORS                   627
#define IDC_PERSISTENCE                 628
#define IDC_PERSISTENCEMIN              629
#define IDD_RUNMETAGOALS                630
#define IDC_PERSISTENCESTDDEV           631
#define IDC_STDDEVLABEL                 632
#define IDC_MINLABEL                    633
#define IDC_SCHEDULEDPOLICY             634
#define IDC_MAXLABEL                    635
#define IDC_AND                         636
#define IDC_OR                          637
#define IDC_SHOWSITES                   638
#define IDC_OR2                         639
#define IDD_EXPORTDATADIALOG            640
#define IDC_UPDATE                      641
#define IDD_RUNMODELS                   642
#define IDC_CLEARPREV                   643
#define IDD_POLICYACTORS                644
#define IDC_COMMENT                     645
#define IDD_PPHOSTSESSION               646
#define IDC_DISTANCE                    647
#define IDD_PPCLIENTSESSION             648
#define IDB_BITMAP2                     649
#define IDC_DISTANCELABEL               650
#define IDC_AREALABEL                   651
#define IDB_REWIND                      652
#define IDB_PAUSE                       653
#define IDC_BUTTON1                     654
#define IDC_SHOWHIDE                    655
#define IDC_COMPUTESCORES               656
#define IDC_TILEVIEWS                   657
#define IDC_NEWRUN                      658
#define IDC_NEW                         659
#define IDC_FROMQUERYBUILDER            660
#define IDC_NEW2                        660
#define IDC_BROWSE                      661
#define IDC_RUNSINGLE                   662
#define IDC_BROWSEHEXCSV                662
#define IDC_QUERYVIEWER                 663
#define IDC_RUNPOLICYEDITOR             664
#define IDC_MORE_LESS                   665
#define IDC_DEFINEQUERY                 666
#define IDC_CHECKERRORS                 667
#define IDB_PLAY                        668
#define IDC_SHOWMYPOLICIES              669
#define IDC_CASCADEVIEWS                670
#define IDC_TOQUERYBUILDER              671
#define IDC_RUNSINGLE2                  672
#define IDC_RUNMULTIPLE                 673
#define IDC_BROWSESCENARIOS             674
#define IDC_BROWSESOURCEBMP             675
#define IDC_SHOWSHAREDPOLICIES          676
#define IDC_TOQUERYBUILDER2             677
#define IDC_SPCONTQUERYBUILDER          678
#define IDC_IDULIST                     679
#define IDC_BROWSELULCTREE              680
#define IDC_BROWSEINDEXBMP              681
#define IDC_IDUTEXT                     682
#define IDC_BROWSEFIELDINFO             683
#define IDC_BROWSEACTORS                684
#define IDC_BROWSERNDX                  685
#define IDC_REMOVEIDU                   686
#define IDC_USESTARTDATE                687
#define IDC_ADDFIELDINFO                688
#define IDC_ADDIDUTEXT                  689
#define IDC_USEENDDATE                  690
#define IDC_REMOVEFIELDINFO             691
#define IDC_ADDCURRENTIDU               692
#define IDC_ISSHAREABLE                 693
#define IDC_ISSHARED                    694
#define IDC_RUNSCENARIOEDITOR           695
#define IDC_ISEDITABLE                  696
#define IDC_RUNLULCEDITOR               697
#define IDC_RUNFIELDEDITOR              698
#define IDC_RUNACTOREDITOR              699
#define IDCANCELBUTTON                  704
#define IDD_DISTANCEDLG                 706
#define IDD_SITEATTR                    708
#define IDC_SITES                       708
#define IDC_EVALFREQSPIN                709
#define IDD_NEWPOLICY                   710
#define IDC_YEARSTORUNEDIT              710
#define IDC_PERCENTCOVERAGEEDIT         711
#define IDC_LAYERS                      713
#define IDC_MAPLAYERS                   713
#define IDD_USER                        714
#define IDC_GRAPHS                      714
#define IDC_TABLES                      715
#define IDC_VIEWS                       715
#define IDC_EXPERIMENTS                 715
#define IDC_SCENARIOS                   715
#define IDC_EXPGRID                     716
#define IDB_SPLASHTEXT                  717
#define IDC_COMBO1                      717
#define IDC_DEFINESCENARIOS             718
#define IDR_TOOLBAR1                    719
#define IDC_FROMQUERY                   719
#define IDC_TOQUERY                     720
#define IDD_ADDMAPVIEW                  721
#define IDC_SPATIALCONTAINER            721
#define IDC_COLUMNLIST                  721
#define IDC_LB_IDD_EVAL_MODEL_LEARN_DLG 721
#define IDC_ATTRIBUTES                  721
#define IDC_TOQUERY2                    721
#define IDC_THISQUERY                   721
#define IDD_VIEWS                       722
#define IDD_VIEWBAR                     722
#define IDB_BUTTON_END                  723
#define IDC_WIDTH                       723
#define IDB_BUTTON_START                724
#define IDC_DECIMALS                    724
#define IDC_QUERYLABEL                  724
#define IDC_FORMAT                      724
#define IDB_BUTTON_PAUSE                725
#define IDC_LABELLOCATION               725
#define IDC_QUERYLABEL2                 725
#define IDB_BUTTON_REWIND               726
#define IDC_LOCATION                    726
#define IDB_BUTTON_END1                 727
#define IDB_BUTTON_STOP                 727
#define IDD_EXPERIMENT                  727
#define IDC_LABELSCALE                  727
#define IDB_EXPGRID                     728
#define IDC_SCALE                       728
#define IDB_BUTTON_START_LEFT           729
#define IDC_LABELSHAPE                  729
#define IDD_VULNERABILITY               730
#define IDC_SHAPE                       730
#define IDD_FIELDCHOOSER                731
#define IDC_PLOTFRAME                   731
#define IDD_MERGE                       732
#define IDD_ADDDBCOL                    733
#define IDC_FIELDTOWEIGHT               733
#define IDD_VARDIST                     734
#define IDC_LINKFIELD                   734
#define IDC_RED                         734
#define IDD_AREA_WT                     735
#define IDC_GREEN                       735
#define IDD_MULTISANDBOXDLG             736
#define IDC_BLUE                        736
#define IDD_SETPOLICYCOLORS             737
#define IDD_EVAL_MODEL_LEARN_DLG        738
#define IDD_AREAQUERY                   739
#define IDD_FIELDINFO                   740
#define IDC_LIST_IDD_EVAL_MODEL_LEARN_DLG 741
#define IDC_LC_IDD_EVAL_MODEL_LEARN_DLG 741
#define IDD_ADJACENCY                   741
#define IDC_VALUE                       742
#define IDC_LEVEL1                      743
#define IDC_COLORS                      744
#define IDB_BITMAP5                     744
#define IDB_SPLASH                      744
#define IDD_POLICYEDITOR                745
#define IDC_SPIN                        746
#define IDD_INIBASIC                    746
#define IDC_MIN                         747
#define IDD_INIACTORS                   747
#define IDC_MAX                         748
#define IDD_INILAYERS                   748
#define IDC_SPIN4                       749
#define IDD_INIMODELS                   749
#define IDC_UNITS                       749
#define IDD_INIEDITOR                   750
#define IDC_ADDALL                      751
#define IDD_SCENARIO                    751
#define IDC_REMOVE                      752
#define IDC_SPLASH                      752
#define IDD_CONTROLPANEL                752
#define IDC_PAP_SOURCELAYER             753
#define IDC_REMOVEALL                   753
#define IDD_SELECTTABLE                 753
#define IDC_MODREMOVE                   753
#define IDC_PAP_TARGETLAYER             754
#define IDC_MOVEUP                      754
#define IDD_CALCULATEFIELD              754
#define IDC_PAP_TARGETFIELD             755
#define IDC_MOVEDOWN                    755
#define IDC_TAB                         756
#define IDD_IDUINFO                     756
#define IDC_BROWSEDATABASE              757
#define IDD_COMPARERUNRESULTS           757
#define IDC_IDU                         758
#define IDD_REACHTREE                   758
#define IDD_WIZARD                      759
#define IDC_INTERVAL                    760
#define IDC_DEBUG                       761
#define IDC_NOBUFFER                    762
#define IDC_MAPOUTPUTS                  763
#define IDC_LABELINTERVAL               764
#define IDC_APPVARS                     767
#define IDC_DECISIONFREQ                768
#define IDC_ASSOCVALUES                 769
#define IDC_ASSOCNEIGHBORS              770
#define IDC_INCLUDEDATA                 770
#define IDC_GRID                        771
#define IDC_PREFERENCE                  772
#define IDC_ADDLAYER                    773
#define IDC_REMOVELAYER                 774
#define IDC_LABELLAYER                  775
#define IDC_PATHLAYER                   776
#define IDC_BROWSELAYERS                777
#define IDC_ADDAPS                      778
#define IDC_REMOVEAPS                   779
#define IDC_LABELAP                     780
#define IDC_PATHAP                      781
#define IDC_ID                          782
#define IDC_BROWSEAPS                   783
#define IDC_PREYEAR                     784
#define IDC_POSTYEAR                    785
#define IDC_USECOL                      786
#define IDC_LABELFIELD                  787
#define IDC_FIELD                       788
#define IDC_TOLAYER                     789
#define IDC_INITINFO                    789
#define IDC_SOURCEFIELD                 789
#define IDC_SELFISH                     790
#define IDC_MERGEINDEXFIELD             790
#define IDC_ALTRUISTIC                  791
#define IDC_TARGETINDEXFIELD            791
#define IDC_SHOWINRESULTS               792
#define IDC_SHOWUNSCALED                793
#define IDC_CDF                         794
#define IDC_LABELMIN                    795
#define IDC_LABELMAX                    796
#define IDC_PLACEHOLDER                 797
#define IDC_SAVEAS                      798
#define IDC_LABELUNITS                  798
#define IDC_ATTR                        799
#define IDC_MODELVARS                   800
#define IDC_ORIGINATOR                  804
#define IDC_COMBO2                      805
#define IDC_DISTRIBUTION                805
#define IDC_COLNODE                     805
#define IDC_INTERSECTLAYER              805
#define IDC_HISTORY                     805
#define IDC_COLTONODE                   806
#define IDC_OUTCOME                     807
#define IDC_COLFROMNODE                 807
#define IDC_OUTCOMELIST                 808
#define IDC_COLORDER                    808
#define IDC_COLTREEID                   808
#define IDC_COLORDER2                   809
#define IDC_SYSLINK1                    810
#define IDC_COLREACHINDEX               810
#define IDC_BUTTON3                     811
#define IDC_ADDWMS                      811
#define IDC_PROBABILITY                 812
#define IDC_EXPIRE                      815
#define IDC_DELAY                       816
#define IDC_EXPIREPERIOD                817
#define IDC_L1EXPIRE                    818
#define IDC_L2EXPIRE                    819
#define IDC_L1DELAY                     820
#define IDC_L1PERSIST                   821
#define IDC_L2PERSIST                   822
#define IDC_EDITSCENARIO                823
#define IDC_EDITPOLICY                  824
#define IDC_SLIDERVALUE                 826
#define IDC_SELF                        826
#define IDC_INITSTR                     827
#define IDC_EVALFREQ                    827
#define IDC_RAWSCORELABEL               828
#define IDC_RAWSCOREMINLABEL            829
#define IDC_POLICYPREF                  829
#define IDC_RAWSCOREMAXLABEL            830
#define IDC_BUFFEREDIT                  830
#define IDC_ADDPOINTEDIT                831
#define IDC_FIELDDESCRIPTION            832
#define IDC_ADDPOINTEDIT2               833
#define IDC_INCREMENTEDIT               833
#define IDC_FILES                       834
#define IDC_EXPANDEDIT                  834
#define IDC_USEQUANTITYBINS             835
#define IDC_FORMULA                     837
#define IDC_FIELDS1                     838
#define IDC_QUERYSOURCE                 839
#define IDC_TREE                        840
#define IDC_USESPECIFIEDVALUE           842
#define IDC_LABELDISTRIBUTION           843
#define IDC_AVAILABLE                   844
#define IDC_USEATTR                     845
#define IDC_TESTORDER                   846
#define IDC_POPULATETREEID              846
#define IDC_LABELNODESGENERATED         847
#define IDC_LABELROOTSGENERATED         847
#define IDC_LABELSINGLENODEREACHES      848
#define IDC_LABELTONODE                 849
#define IDC_LABELFROMNODE               850
#define IDC_POPULATEREACHINDEX          850
#define IDC_LABELORDER                  851
#define IDC_LABELTREEID                 851
#define IDC_LABELORDER2                 852
#define IDC_EXPLORE_IDU_COVERAGE        852
#define IDC_POPULATEORDER               853
#define IDC_SETUP_IDU_DB                853
#define IDC_LABELPHANTOMSGENERATED      854
#define IDC_EDIT_POLICIES               854
#define IDC_EDIT_SCENARIOS              855
#define IDC_LABELREACHINDEX             855
#define IDC_RUN_SCENARIO                856
#define IDC_LABELFLOWGRID               856
#define IDC_CREATE_PROJECT              857
#define IDC_LABELROOTSGENERATED2        857
#define IDC_PA_EFFECTIVENESS            870
#define IDC_PA_TOLERANCE                871
#define IDC_PA_PLOTFRAME                872
#define IDC_PA_STATIC1                  873
#define IDC_PA_STATIC2                  874
#define IDC_QUERY                       880
#define IDC_REFRESH                     881
#define IDS_MODELINFO                   900
#define IDS_PROGRESS                    901
#define IDS_RUNPROGRESS                 902
#define IDC_DATA_SET_COMBO              1000
#define IDC_DEFAULTPERIOD               1000
#define IDCC_RESULTS                    1000
#define IDC_INSTALLCOST                 1001
#define IDC_POINT_SIZE_COMBO            1001
#define IDC_CALC_SLOPES                 1002
#define IDC_SOILVALUE                   1002
#define IDC_POINT_TYPE_COMBO            1002
#define IDC_BUTTON2                     1002
#define IDC_SEARCH                      1002
#define IDC_ADDFIELD                    1002
#define IDC_IMPORT                      1002
#define IDC_SLOPE_FIELD                 1003
#define IDC_RENTALRATE                  1003
#define IDC_DATASOURCES                 1003
#define IDC_PROGRESS                    1004
#define IDC_INCOME                      1004
#define IDC_COLOR_STATIC                1004
#define IDC_DSLABEL                     1004
#define IDC_LAYERNAME                   1005
#define IDC_OTHERCOSTS                  1005
#define IDC_LANDVALUE                   1005
#define IDC_FIND                        1005
#define IDC_FINDSTRING                  1005
#define IDC_FILE                        1006
#define IDC_REPLACESTRING               1006
#define IDC_TYPE                        1007
#define IDC_MATCH_ENTIRE                1007
#define IDC_SEARCH_THIS                 1008
#define IDC_SEARCH_SELECTED             1009
#define IDC_SEARCH_UP                   1010
#define IDC_FINDALL                     1011
#define IDC_REPLACELABEL                1012
#define IDC_COLORRAMP                   1014
#define IDC_MAPUNITS                    1014
#define IDC_DATAFIELD                   1015
#define IDC_BINCOUNT                    1016
#define IDC_PROGRESS1                   1016
#define IDC_SPIN1                       1017
#define IDC_PATHFIELDINFO               1017
#define IDC_MAXDISTANCE                 1017
#define IDC_MEAN                        1017
#define IDC_COMPLIANCE                  1017
#define IDC_UNIQUEVALUES                1018
#define IDC_SPIN2                       1018
#define IDC_ASSOCNONE                   1018
#define IDC_GENERATEBINS                1019
#define IDC_SPIN3                       1019
#define IDC_NOACTORS                    1019
#define IDC_AREAWTMEAN                  1019
#define IDC_BINLIST                     1020
#define IDC_IDU_WTS                     1020
#define IDC_FIELDTYPE                   1021
#define IDC_STDDEV                      1021
#define IDC_LABELQUERY                  1023
#define IDC_LABELNAME                   1024
#define IDC_RVALUE                      1025
#define IDC_LABELCOLOR                  1025
#define IDC_PVALUE                      1026
#define IDC_LABELACTORS                 1026
#define IDC_CVALUE                      1027
#define IDC_LABELBASIC                  1027
#define IDC_LABELOBJECTIVES             1028
#define IDC_OUTCOMES                    1029
#define IDC_LABELFREQ                   1029
#define IDC_CELLLAYER                   1030
#define IDC_DECADALMAPS                 1030
#define IDC_LABELID                     1030
#define IDC_COLSTOSAVE                  1031
#define IDC_LABELSLIDER                 1031
#define IDC_TABLE                       1032
#define IDC_EXPORTMAP                   1032
#define IDC_DATABASE                    1033
#define IDC_SPININTERVAL                1033
#define IDC_IMPORTANCE                  1034
#define IDC_LABELYRS                    1034
#define IDC_TEMPERATURE                 1035
#define IDC_LULCTREE                    1035
#define IDC_CATEGORIES                  1035
#define IDC_EXPORTOUTPUT                1035
#define IDC_FIELDINFO                   1036
#define IDC_MEMORY                      1036
#define IDC_EXPORTBMPS                  1036
#define IDC_ERRORLIST                   1037
#define IDC_SEDIMENTS                   1038
#define IDC_ALTRUISM                    1038
#define IDC_PESTICIDES                  1039
#define IDC_OBJECTIIVES                 1039
#define IDC_RUN_RESOPTIONS              1040
#define IDC_PERSISTENCEMAX              1040
#define IDC_MODADD                      1040
#define IDC_DESC                        1041
#define IDC_MAXANNUALVALUE              1041
#define IDC_THRESHOLD                   1042
#define IDC_USEQUERY                    1042
#define IDC_DESC2                       1042
#define IDC_RULESETS                    1043
#define IDC_POLICIES                    1043
#define IDC_PREVIOUS_RULESET            1044
#define IDC_PREVPOLICY                  1044
#define IDC_NOTEXT                      1044
#define IDC_NEXT_RULESET                1045
#define IDC_NEXTPOLICY                  1045
#define IDC_EXPR                        1045
#define IDC_RULES                       1046
#define IDC_RADIO1                      1046
#define IDC_PREVIOUS_RULE               1047
#define IDC_RADIO2                      1047
#define IDC_NEXT_RULE                   1048
#define IDC_TEXTLABEL                   1049
#define IDC_OBSERVATIONS                1049
#define IDC_TEXT                        1050
#define IDC_FLOWDIRGRID                 1050
#define IDC_VARVALUES                   1051
#define IDC_SAVEPRJ                     1051
#define IDC_SATISIFIED                  1052
#define IDC_SAVEEXTERNAL                1052
#define IDC_CONSTRAINTS                 1053
#define IDC_PREVIOUS_CONSTRAINT         1054
#define IDC_POPULATECOUNT               1054
#define IDC_USEEDGEID                   1054
#define IDC_USETOQUERY                  1054
#define IDC_NEXT_CONSTRAINT             1055
#define IDC_POSITION                    1055
#define IDC_USETHISQUERY                1055
#define IDC_SHOWRULES                   1056
#define IDC_SHOWCONSTRAINTS             1057
#define IDC_LAYER                       1057
#define IDC_8BIT                        1058
#define IDC_GRIDVIEW                    1059
#define IDC_SHOWMATCHING                1060
#define IDC_CURRENTSELECTION            1061
#define IDC_SPATIAL                     1061
#define IDC_VISIBLE                     1062
#define IDC_POPMERGEINDEX               1062
#define IDC_FRAMETEXT                   1063
#define IDC_POPTARGETINDEX2             1063
#define IDC_POPTARGETINDEX              1063
#define IDC_IDFIELD                     1063
#define IDC_POPTARGETLAYER              1064
#define IDC_TEXTFIELD                   1064
#define IDC_CREATEFIELDINFO             1065
#define IDC_TARGETLAYER                 1066
#define IDC_MERGEFIELD                  1068
#define IDC_TARGETFIELD                 1069
#define IDC_MAJORITY                    1070
#define IDC_PERCENTFIELDS               1071
#define IDC_GRIDSIZE                    1072
#define IDC_SUM                         1073
#define IDC_MAJORITY2                   1074
#define IDC_AVERAGE                     1074
#define IDC_STATUS                      1075
#define IDC_SAVESOURCE                  1077
#define IDC_SOURCERASTERPATH            1078
#define IDC_SAVEINDEX                   1079
#define IDC_INDEXPATH                   1080
#define IDC_INDEXRASTERPATH             1080
#define IDC_USERNDX                     1081
#define IDC_SOURCERASTERPATH2           1082
#define IDC_SAVERNDX                    1083
#define IDC_COLS                        1085
#define IDC_ROWS                        1086
#define IDC_TARGETFIELDTOPOPULATE       1087
#define IDC_RUN                         1088
#define IDC_STATUSTEXT                  1089
#define IDC_SETUP                       1091
#define IDC_SETOUTLINECOLOR             1092
#define IDC_ADDMAPLAYER                 1093
#define IDC_LABELEDGEID                 1094
#define IDC_SELECTED                    1095
#define IDC_ADDGRAPH                    1096
#define IDC_USEALTRUISM                 1096
#define IDC_LABELNODE                   1097
#define IDC_USEACTORVALUES              1097
#define IDC_USEPOLICYPREFS              1098
#define IDC_USEUTILITY                  1099
#define IDC_ADDVIEW                     1100
#define IDC_USEPROBABILSTIC             1100
#define IDC_USEPROBABILISTIC            1100
#define IDC_IDUCOUNT                    1101
#define IDC_USEMAX                      1101
#define IDC_SAVE_THIS_SESSION           1102
#define IDC_SELIDUONLY                  1103
#define IDC_ALL                         1103
#define IDC_SAVE_TO_FILE                1104
#define IDC_SELECTIDUBTN                1105
#define IDC_SELECTEDONLY                1105
#define IDC_OPTIONS                     1106
#define IDC_SUMMARY                     1107
#define IDC_INCLUDEDUPLICATES           1107
#define IDC_CHECK                       1108
#define IDC_CHECK3                      1108
#define IDC_SELECTEDDATES               1108
#define IDC_LANDUSES                    1109
#define IDC_INHERITFROMPARENT           1110
#define IDC_CURRENTTYPE                 1110
#define IDC_MAINTENANCECOST             1111
#define IDC_USEFORMAT                   1111
#define IDC_FRAME                       1112
#define IDC_STATICLABEL                 1112
#define IDC_DURATION                    1112
#define IDC_ANALYSIS_PERIOD             1113
#define IDC_STATICID                    1113
#define IDC_FIELDBORDERWIDTH2           1114
#define IDC_RIPARIANBUFFERWIDTH3        1114
#define IDC_LOW_IMPACT_RECREATION       1115
#define IDC_THRESHOLDVALUE              1115
#define IDC_MFCBUTTON1                  1115
#define IDC_RIPARIANBUFFERWIDTH2        1116
#define IDC_SCORES                      1116
#define IDC_SUMMARYLABEL                1117
#define IDC_STATICMODEL                 1117
#define IDC_MODEL                       1118
#define IDC_PROGRESSTEXT                1119
#define IDC_RECLASSVALUES               1120
#define IDC_ENVXFILE                    1200
#define IDC_BROWSEENVX                  1201
#define IDC_LULC_USEENVX                1202
#define IDC_LULC_USEXML                 1203
#define IDC_LULC_NOSAVE                 1204
#define IDC_LULCFILE                    1205
#define IDC_BROWSELULC                  1206
#define IDC_POLICY_USEENVX              1212
#define IDC_POLICY_USEXML               1213
#define IDC_POLICY_NOSAVE               1214
#define IDC_POLICYFILE                  1215
#define IDC_BROWSEPOLICY                1216
#define IDC_LB_MODELS_IDD_EVAL_MODEL_LEARN_DLG 1218
#define IDC_VARS                        1218
#define IDC_SELECTALL                   1219
#define IDC_USE                         1219
#define IDC_SELECTNONE                  1220
#define IDC_VIEWCURRENT                 1220
#define IDC_UNIFORM                     1221
#define IDC_SCENARIO_USEENVX            1222
#define IDC_RANDOM                      1222
#define IDC_SCENARIO_USEXML             1223
#define IDC_COUNT                       1223
#define IDC_SCENARIO_NOSAVE             1224
#define IDC_GENERATE                    1224
#define IDC_SEND                        1224
#define IDC_PMP_INDEPENDENTRUN          1224
#define IDC_PDD_EXIT                    1224
#define IDC_RUNSANDBOXBUTTON            1224
#define IDC_MAXMIN                      1224
#define IDC_YEARINTERVAL                1224
#define IDC_SCENARIOFILE                1225
#define IDC_RADIO3                      1225
#define IDC_CURRENT                     1225
#define IDC_EXPORTDATA                  1225
#define IDC_SINGLE                      1225
#define IDC_USECATEGORYBINS             1225
#define IDC_USEVERTICES                 1225
#define IDC_SEARCH_ALL                  1225
#define IDC_IDU_GROUPS                  1225
#define IDC_NOSAVE                      1225
#define IDC_MAX_COUNT                   1225
#define IDC_BROWSESCENARIO              1226
#define IDC_LULCA                       1226
#define IDC_NONE                        1226
#define IDC_LULCB                       1227
#define IDC_LULCC                       1228
#define IDC_LULCTREECTRL                1229
#define IDC_COLLECTLULCTRENDS           1230
#define IDC_SCNDESCRIPTION              1231
#define IDC_EXPAND                      1231
#define IDC_SCROLLBAR                   1231
#define IDC_STARTVALUES                 1232
#define IDC_LABEL                       1232
#define IDC_FIELDLIST                   1233
#define IDC_BALANCE                     1233
#define IDC_EXPORTBUTTON                1233
#define IDC_DISCONNECT                  1233
#define IDC_SLIDER1                     1234
#define IDC_DISCONNECTALL               1234
#define IDC_SLIDER                      1234
#define IDC_EXPAND3                     1234
#define IDC_SLIDERSELF                  1234
#define IDC_USESTARTVALUE               1235
#define IDC_PRIORITYWTSLIDER            1235
#define IDC_SLIDERALTRUISM              1235
#define IDC_SOURCE                      1236
#define IDC_POLICYCONSTRAINTS           1236
#define IDC_PINGALL                     1236
#define IDC_SLIDERPOLICYPREF            1236
#define IDC_USEENDVALUE                 1237
#define IDC_STARTSESSION                1237
#define IDC_GLOBALCONSTRAINTS           1238
#define IDC_STOPSESSION                 1238
#define IDC_TARGET                      1239
#define IDC_STARTVALUES2                1240
#define IDC_ENDVALUES                   1241
#define IDC_RESOURCE_LIMIT              1242
#define IDC_MAX_AREA                    1244
#define IDC_FIELDS                      1245
#define IDC_MAXVALUE_LABEL              1246
#define IDC_VALUES                      1246
#define IDC_ADDGC                       1248
#define IDC_OPERATORS                   1250
#define IDC_UNIT_AREA                   1256
#define IDC_ADDPOLICYCONSTRAINT         1260
#define IDC_YES                         1262
#define IDC_FUNCTIONS                   1266
#define IDC_MAX_AREA2                   1267
#define IDC_ABSOLUTE                    1268
#define IDC_NOPE                        1269
#define IDC_GCCOMBO                     1270
#define IDC_GC_LABEL                    1272
#define IDC_GLOBALEFF                   1273
#define IDC_GC_LABEL2                   1273
#define IDC_MAINENANCECOST_LABEL        1274
#define IDC_RUNGLOBAL                   1275
#define IDC_INITCOST_LABEL              1276
#define IDC_LULC_NOSAVE2                1277
#define IDC_XEYE                        1278
#define IDC_INITIALCOST                 1279
#define IDC_YEYE                        1280
#define IDC_DURATION_LABEL              1281
#define IDC_ZEYE                        1282
#define IDC_YEAR_LABEL                  1283
#define IDC_XCENTER                     1284
#define IDC_MAINTENANCECOST_LABEL       1285
#define IDC_YCENTER                     1286
#define IDC_ZCENTER                     1287
#define IDC_PIXELSIZE                   1288
#define IDC_XUP                         1289
#define IDC_PIXELSIZE_LABEL             1290
#define IDC_YUP                         1291
#define IDC_MAPUNITS_LABEL              1292
#define IDC_ZUP                         1293
#define IDC_CHECK1                      1294
#define IDC_APP                         1294
#define IDC_APPLICATION                 1294
#define IDC_DISABLE                     1294
#define IDC_INTERACTIONS                1294
#define IDC_CAPTUREINTERVAL             1295
#define IDC_ONUPDATE                    1296
#define IDC_FOV                         1297
#define IDC_3D                          1298
#define IDC_2D                          1299
#define IDC_APPLY                       1300
#define IDC_DEFAULTS                    1301
#define IDC_YEARSTORUN                  1302
#define IDC_YEARS                       1311
#define IDC_ITERATIONS                  1312
#define IDC_RICHTEXT                    1313
#define IDC_STARTYEAR                   1314
#define IDC_ACTORS                      1315
#define IDC_STARTYEAR2                  1315
#define IDC_ENDYEAR                     1316
#define IDC_LULCLEVEL                   1317
#define IDC_LULCCLASS                   1318
#define IDC_SETCOLOR                    1319
#define IDC_COLOR                       1320
#define IDC_DELETEGC                    1321
#define IDC_OBJECTIVES                  1322
#define IDC_DELETEPOLICYCONSTRAINT      1323
#define IDC_WTSLIDER                    1324
#define IDC_ADDGLOBALCONSTRAINT         1324
#define IDC_HATCHPATTERN                1325
#define IDC_OUTLINECOLOR2               1326
#define IDC_NEXT                        1327
#define IDC_COPY                        1328
#define IDC_DELETE                      1329
#define IDC_PREV                        1330
#define IDC_EDITFIELDINFO               1331
#define IDC_FREQ                        1332
#define IDC_PERSIST                     1333
#define IDC_FREQ2                       1334
#define IDC_PRIORITY                    1335
#define IDC_AREA                        1336
#define IDC_PERSISTCHECK                1337
#define IDC_REG                         1338
#define IDC_ALTMANAGEMENT               1339
#define IDC_COLUMNS                     1340
#define IDC_POPLULC                     1341
#define IDC_ENABLEPOLICYMETAPROCESS     1342
#define IDC_ENABLECULTURALMETAPROCESS   1343
#define IDC_DYNAMICUPDATE               1344
#define IDC_DYNAMICUPDATEVIEWS          1345
#define IDC_POLICYFREQUENCY             1346
#define IDC_DYNAMICUPDATEMAP            1347
#define IDC_POLICYFREQUENCY_LABEL       1350
#define IDC_CULTURALFREQUENCY_LABEL     1351
#define IDC_COLLECTACTORDATA            1352
#define IDC_CULTURALFREQUENCY           1353
#define IDC_COLLECTLANDSCAPESCOREDATA   1354
#define IDC_EVALFREQUENCY               1400
#define IDC_COLLECTPOLICYDATA           1401
#define IDC_MANDATORY                   1402
#define IDC_OVERWRITE                   1404
#define IDC_LOADSHAREDPOLICIES          1405
#define IDC_ASSOCATTR                   1406
#define IDC_USEVAR                      1407
#define IDC_SPECMINVAL                  1408
#define IDC_DEFAULT                     1410
#define IDC_POPULATENEARESTINDEX        1411
#define IDC_MATCH_CASE                  1412
#define IDC_POPULATENEARESTVALUE        1412
#define IDC_SHOWTIPS                    1413
#define IDC_RUNINIEDITOR                1414
#define IDC_CHECKFORUPDATES             1414
#define IDC_EXCLUSIVE                   1415
#define IDC_SITEATTR                    1416
#define IDC_SPECMAXVAL                  1417
#define IDC_MANDATORY2                  1418
#define IDC_SCHEDULED                   1419
#define IDC_ISSCHEDULED                 1420
#define IDC_LULCALABEL                  1421
#define IDC_LULCAID                     1422
#define IDC_LULCBID                     1423
#define IDC_LULCCLABEL                  1424
#define IDC_LULCBLABEL                  1425
#define IDC_LULCCID                     1426
#define IDC_DONE                        1427
#define IDC_LIST1                       1428
#define IDC_LIST2                       1429
#define IDC_WMSLAYERS                   1429
#define IDC_DATALIST                    1430
#define IDC_USERS                       1431
#define IDC_RUNS                        1432
#define IDC_METAGOALS                   1433
#define IDC_LOOKUPTABLE                 1501
#define IDC_SELECTALLFIELDS             1506
#define IDC_UNSELECTALLFIELDS           1507
#define IDC_BAR                         1508
#define IDC_SUBMENU                     1509
#define IDC_ADDSUBMENU                  1510
#define IDC_FIELDTREE                   1512
#define IDC_WINDOWS                     1513
#define IDC_FRAMERATE                   1514
#define IDC_QUALITY                     1515
#define IDC_FRAMERATELABEL              1520
#define IDC_SECONDSLABEL                1521
#define IDC_CAPTUREQUALITYLABEL         1522
#define IDC_PERCENTLABEL                1523
#define IDC_MILLISECONDSLABELS          1524
#define IDC_MILLISECONDSLABEL           1524
#define IDC_PATHLABEL                   1525
#define IDC_HEXFROMPOINTS               1526
#define IDC_HEXCSVFILE                  1527
#define IDC_LABEL_HEXCSVFILE            1528
#define IDC_CENTROIDS_CSV               1529
#define IDC_HEXCSV_INPUT                1530
#define IDC_VOROINI                     1531
#define IDC_LABEL_XCOL                  1532
#define IDC_LABEL_YCOL                  1533
#define IDC_XCOL                        1534
#define IDC_HEXRADIUS                   1535
#define IDC_YCOL                        1536
#define IDC_LABEL_RADIUS                1537
#define IDC_COPYDATA                    1538
#define IDC_VERSION                     1539
#define IDC_ADDTOMAP                    1540
#define IDC_STUDYAREAS                  1540
#define IDC_UPDATETEXT                  1541
#define IDC_PERTURBATION                1543
#define IDC_OUTPUT                      1544
#define IDC_EDIT1                       1546
#define IDC_LOCALPATH                   1546
#define IDC_IDUFIELD                    1547
#define IDC_WMSPATH                     1549
#define IDC_USELOCAL                    1550
#define IDC_USEWMS                      1551
#define IDC_WMSLIST                     1552
#define IDC_QUERYBUILDER                1600
#define IDCC_RTVIEWS                    2000
#define IDS_DIDYOUKNOW                  2143
#define IDS_TIP_FILE_MISSING            2144
#define IDS_WELCOME                     2145
#define IDCC_DATATABLE                  3000
#define IDD_POLICYOUTCOME               4445
#define IDD_EDITOUTCOME                 4446
#define IDD_OUTCOMEEDITOR               4446
#define IDD_ADDRESULT                   4447
#define IDD_SCENARIOEDITOR              4448
#define IDD_REMOVEDBCOL                 4449
#define IDD_INISETTINGS                 4450
#define IDD_LULCEDITOR                  4451
#define IDD_TIPOFTHEDAY                 4452
#define IDD_FINDDATA                    4453
#define IDD_OPTIONS                     4454
#define IDD_NEWINI_STEP2                4455
#define IDD_NEWINI_FINISH               4456
#define IDB_RESULTS_LARGE               4457
#define IDD_NEWINI_STEP3                4457
#define IDB_RESULTS_SMALL               4458
#define IDB_RTVIEWS_LARGE               4460
#define IDB_RTVIEWS_SMALL               4461
#define IDD_SPATIALINDEX                4462
#define IDD_INILAYERS1                  4463
#define IDD_INIPROCESSES                4464
#define IDD_HISTOGRAM                   4465
#define IDD_DELTAREPORT                 4466
#define IDD_LOAD                        4467
#define IDD_POLICYOBJSCORES             4468
#define IDD_POLQUERYBUILDER             4469
#define IDD_SAVEXMLOPTIONS              4470
#define IDD_AREASUMMARY                 4471
#define IDD_LINEDENSITY                 4472
#define IDD_TASTERIZE                   4473
#define IDD_RASTERIZE                   4473
#define IDD_SCENARIOGRID                4474
#define IDD_TEXT_TO_ID                  4475
#define IDD_INTERSECT                   4476
#define IDD_DIALOG1                     4478
#define IDD_POLICY_SCENARIOS            4478
#define IDD_CONSTRAINTS                 4479
#define IDD_SAVETO                      4480
#define IDD_DIALOG2                     4481
#define IDD_DELTAEXPORT                 4481
#define IDD_CHANGETYPE                  4482
#define IDD_INIMETAGOALS                4483
#define IDD_RECLASS                     4484
#define IDD_SAVEPROJECT                 4485
#define IDD_POLICYCONSTRAINTS           4486
#define IDD_OUTCOMECONSTRAINTS          4487
#define IDD_GLOBALCONSTRAINTS           4488
#define IDB_FIELDINFOEDITOR             4488
#define IDD_DELTAVIEWER                 4489
#define IDD_DELTAVIEWEREX               4490
#define IDD_VIDEORECORDER               4491
#define IDD_CONVERTCOVERAGE             4493
#define IDD_UPDATE                      4495
#define IDD_DIALOG3                     4496
#define IDD_UPDATE2                     4496
#define IDD_SENSITIVITY                 4497
#define IDB_SPLASH7                     4503
#define IDD_BASEMAP                     4504
#define IDCC_ANALYTICS                  5000
#define ID_SHOWRESULTS                  30000
#define ID_SHOWDELTAS                   30001
#define ID_RUNQUERY                     30002
#define ID_ATTRPLOT                     30003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        4506
#define _APS_NEXT_COMMAND_VALUE         513
#define _APS_NEXT_CONTROL_VALUE         1553
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
